#!/bin/bash

rm -rf ~/projects/F1C200S-Dev-board/buildroot/output/build/linux-6.19.11 
rm -f ~/projects/F1C200S-Dev-board/buildroot/.stamp_defconfig 
make -C ~/projects/F1C200S-Dev-board defconfig 
make -C ~/projects/F1C200S-Dev-board -j8
